### ISSUE TITLE
Cleanup warnings (Unneeded casting)

### ISSUE THREAD

**Issue by Arnuh** [Arnuh/EchoPet#1]
Also might as well @TNTUP ... added a release for 1.12

**Comment by TNTUP** [comment]
:O Didn't expect Echopet coming back to 1.12! You made my day! Will test it when I have time and idk what to say... BIG thanks to you and donating for your work (is it much 10$USD?) 

Again big thanks to you <3 If anyone asks the download link should I link to this github or if it gets deleted (I hope not!) providing EchoPet-1.12.jar from my server? I did for 1.10 and 1.11. I'll recommend myself to this github for a much safer place to download it :)

EDIT: Works in usual (didn't test completely) tried Vex, Vindicator, Evoker, Parrot, Llama, Iron Golem, Illusioner <3 

Noticed in the console (in red) like it couldn't identify WorldGuard "[22:44:21] [Server thread/INFO]: [EchoPet][0;31;1m [WARNING] Could not create a PluginDependencyProvider for: WorldGuard! (Are you sure the type is valid?) - String index out of range: -2[m" but harmless I guess, I have ignored it (anyways I don't think I should disable pets in a region (maybe yes in minigames :P)

**Not needed but something like the "WOLOLO (10sec delay then repeats WOLOLO? X D)" thing for Evokers, Vindicator's Axe (like powered mode) and Illusioner to 4 fake illusioners (Invisibilty effect I noticed)

EDIT: Illusioner does not make any sounds, others does (Parrots) :P

EDIT2: Should pet Parrots imitate monsters nearby like real parrots do? Not necessarily again xD
