### ISSUE TITLE
Iron Golems throw exception and despawn

### ISSUE THREAD

**Issue by FatherWh0** [Arnuh/EchoPet#105]
When EchoPet is loaded we get the following error and iron golems despawn:
Entity threw exception at water_world:5955.5,51.0,-6021.5
The following is with debug=true in server.properties
https://pastebin.com/RZ15QwVA
EchoPet version: 1.0.8-SNAPSHOT-b31
paper 1.17.1 # 259

**Comment by FatherWh0** [comment]
Further testing shows that the exception only occurs when a player is nearby with a villager pet, baby or adult.

**Comment by Arnuh** [comment]
The commit for #106 should fix this but I have done limited testing outside of making sure this issue & the other crash aren't still reproducible.

Like I mention in #106 this does cause issues where other entities will see the Villager pet as a real Villager and attempt to interact with it in certain scenarios.
