### ISSUE TITLE
Fix wiki page and links

### ISSUE THREAD

**Issue by ghost** [Arnuh/EchoPet#108]
Basically what the title states, would be nice.

**Comment by Arnuh** [comment]
I've done Pet Types(Pet Data is todo) and Config. I assume people will want the command & permission one too.

A temp solution for permissions is just the plugin yml https://github.com/Arnuh/EchoPet/blob/v1_17/src/resources/plugin.yml Most of its self explanatory I feel

**Comment by Arnuh** [comment]
Released a couple more pages that are mostly copypasted from the original wiki with a couple small fixes.

If you have other issues or questions about the wiki I'd like to know.
