### ISSUE TITLE
Sliding pet rabbits and other stuff

### ISSUE THREAD

**Issue by Sandukhan** [Arnuh/EchoPet#11]
I noticed that with the new version of echopets (1.0.4 -b) for 1.12, rabbits arent hopping anymore, they just slide around, following thier owner.

Also how do i properly remove items/options from the pet menu? Just deleting the strings in the config file dosent seems to work, they get recreated by the next server restart.

I was wondering what happend to your spigot page of echopets. Any reason why you removed that?

**Comment by Arnuh** [comment]
looked at fixing, gave up. anyone can pr a fix

Looked at fixing, gave up. anyone can pr a fix.. It properly loads from the config but it randomly adds back the slots grabbing from getLoadedLayout() but the only place it adds tot he layout is in the load method so meh

From my previous response, and maybe my response to other issues. I'm not in the mood to do pretty much any of the work here, atleast not right now. Putting it on spigot people will expect me to keep doing updates to fix all these tiny issues which I usually wont. If no one wants to contribute then I can let the project slowly die and eventually ignore it

**Comment by Sandukhan** [comment]
Sad to hear, because echopets is still a solid build and many server keep using it, especially in 1.8. Still a better pet plugin, than the other stuff i found on spigot so far...
Thx for updating it so long anyway.

About removing Items from the pet menu. I tryed to keep all these strings in config and just replaced the material with "stained_glass_pane", does seems to work, least for now ;P.

**Comment by andrewkm** [comment]
I cannot reproduce this.
My pet rabbits hop around as expected on build 17 running on 1.13.2 Paper Spigot.
Issue can be closed in my opinion.

@Sandukhan if you can provide more information / detailed reproduction steps / environment that would be great.

**Comment by Sandukhan** [comment]
Ya with the latest version of echopet that i found here and the 1.13.2 update, that dosent seems do be a problem any more.

**Comment by andrewkm** [comment]
Awesome! Glad to see it’s resolved :)
