### ISSUE TITLE
Jenkins builds don't work with paper 305

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#112]
https://jenkins.arnah.ca/job/EchoPet-Dev/changes
Error: https://i.imgur.com/vcSNuif.png

**Comment by Arnuh** [comment]
Thought this was only in my custom pets branch but I guess it was due to the powermessage removal. The fix is in the custom pets branch so it'll have to wait until that is merged since I put the fix with a bunch of other changes.

**Comment by Blatower21** [comment]
Having the same issue
