### ISSUE TITLE
Is there a working version of EchoPet for 1.17.1?

### ISSUE THREAD

**Issue by c0wg0d** [Arnuh/EchoPet#115]
I tried to download the source and compile, but I'm getting several compile errors and I don't really know what I'm doing.  If there is a working version, can the jar be added to the Releases section?  Or can you help me get it compiling?

Error: java: package com.dsh105.commodus.config does not exist

**Comment by Arnuh** [comment]
Builds exist in the readme https://github.com/Arnuh/EchoPet#readme

I'd recommend development due to #114 and the minimal breaking changes so far. Using development branch should also allow you to easily compile since a maven repository has been setup with EchoPets depends.

**Comment by c0wg0d** [comment]
Awesome, thank you so much for keeping this plugin updated!  My players love it so much and have really been missing it since we updated to 1.17.1!
