### ISSUE TITLE
Invisible Pets

### ISSUE THREAD

**Issue by ryans1230** [Arnuh/EchoPet#12]
Alright Borlea let me pick your brain with this problem. Every plugin we've tried since 1.11.x has had problems with showing pets to the players. Pets spawn in fine, in terms of no error messages to the user, and no errors in the console. The problem is pets can't be seen by the players in game.

The other plugins we tried had a few different methods for registering the pets. Working with those devs we weren't able to get very far. They came to the conclusion it was broke, or it was based on the gamerule `doMobSpawning`, however I believe that only affects the natural spawning of mobs, not when a plugin is doing it.

Our plugin list is fairly short: EchoPet, LibsDisguises, ProtocolLib, LogBlock, Essentials, BanManager, SuperTrails, WorldEdit, NoCheatPlus, a plot plugin, and a roleplay/chat handling plugin.

The only conflicts I can think of is ProtocolLib or LibsDisguises, however those were never an issue before (all plugins are up to date).

**Comment by Arnuh** [comment]
doMobSpawning doesn't appear to break it.

If you copy your plugins to a local server and disable them 1 by 1 testing if the spawning gets fixed it would be helpful. The only time I remember pets spawning properly but not being visible is due to a plugin conflict from another plugin messing with spawning(Could be libs disguises). The issue is something that came out I think in 1.11

**Comment by ryans1230** [comment]
I'm assuming the event I should be looking at is the CreatureSpawnEvent. Looking at timings, there are only two plugins listening to the event, yours and our custom one. I've attached the code below of our plugin, which I don't believe should be affecting all pet spawning:
```java
SpawnReason reason = event.getSpawnReason();
if ((plugin.getSettings().isDisableIronGolems() && reason == SpawnReason.BUILD_IRONGOLEM)
     || (plugin.getSettings().isDisableSnowmen() && reason == SpawnReason.BUILD_SNOWMAN)
     || (plugin.getSettings().isDisableWithers() && reason == SpawnReason.BUILD_WITHER)) {
     event.getEntity().remove();
}
```

**Comment by andrewkm** [comment]
@ryans1230 the only pets that are invisible for us is Zombie Villager.
I am testing on an environment with latest protocollib, libsdisguise, and 1.13.2 paper spigot.

Please provide more information if you're still experiencing this @ryans1230 otherwise I believe this can be closed for now.
