### ISSUE TITLE
Ender Dragon Riding

### ISSUE THREAD

**Issue by HeadlessJoey** [Arnuh/EchoPet#13]
Hi,

All seems to work in 1.12 except for the Ender Dragon.
I know that the dragon falling through the world is not something you can fix but what about the riding?

Going forward or backwards with the dragon is broken, left and right works fine.
If you could fix that it would be enough for me, the dragon falling through the world is a different issue but something I can live with.

(I did have some other version of echopet in 1.11 where the enderdragon worked fine and didn't fall through the world, not sure if giving you the .jar would help at all? To be honest, I've got no idea where I got it from and I thought it was one of your releases)

**Comment by Arnuh** [comment]
Besides the accidental issue tag with my commit.. I guess the dragon falling has been an issue for over a year now! woo

I'll likely look into this in my freetime after any other issues + missing features are working as ender dragon is an annoying task and easier(and smarter) to just disable for 99% of users.

**Comment by andrewkm** [comment]
https://github.com/Arnuh/EchoPet/issues/37

Added update on latest build in above issue.
