### ISSUE TITLE
1.19.1 has broken EchoPet.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#131]
https://gist.githubusercontent.com/andrewkm/e71f87daec8d3617377bc7ec57dda0ee/raw/7509fec4e9700e3f4c34e24dc3e0e036a95ce040/gistfile1.txt

**Comment by johngonole** [comment]
Just was running it fine on server play.mcball.net

We just upgraded to 1.19.1.  We run this on our hub server.  I have the phantom pet.   Everytime I would go to connect to the server the hub server which is running echopets would crash.  The following in the crash report.

https://s3.amazonaws.com/files.enjin.com/211595/error reports/crash-2022-07-29_06.14.39-server.txt

**Comment by Arnuh** [comment]
https://jenkins.arnah.ca/job/EchoPet-Dev/94/
