### ISSUE TITLE
PetWardens disappear.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#133]
Recently got this report:
TL;DR Pet Wardens disappear after a while.

https://ecocitycraft.com/forum/threads/pet-warden-disappearing.218293/
Video: https://www.youtube.com/watch?v=eIvz1EQUXdU

**Comment by Arnuh** [comment]
Let a warden sit around for 30~ minutes and can't reproduce.

**Comment by andrewkm** [comment]
Bruh @Arnuh yo wardens be on crack... Mike's are in rehab. (Ok lemme do some more investigations and see what's up, we'll share code if we find something).

**Comment by andrewkm** [comment]
I'm stupid, this is our problem.

**Comment by andrewkm** [comment]
Now that I got to my computer, TL;DR this was our entity cleaning plugin affecting pets for some reason, something it didn't do in the past. We've added a none dependent mechanism to expose pets via 2 patches to solve our issue. :)

**Comment by Arnuh** [comment]
Any info on what that is? Need something like a PDC entry or? Might as well add it to base echopet

**Comment by electronicboy** [comment]
I just added a PDC entry to the entity inside of com.dsh105.echopet.api.pet.Pet#spawnPet (basically just right after the spawn call), that way I could identify the pet entity without having to care about depending on the plugin and all that
