### ISSUE TITLE
Add Camels to 1.19.3

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#138]
Add Camels to 1.19.3 <3

**Comment by Arnuh** [comment]
No plans to do this for 1.3.0, would need to wait for 1.4.0 development to start

**Comment by andrewkm** [comment]
Cool thanks for the update man!

**Comment by Arnuh** [comment]
#134 is definitely still needed. Seems to cause some issues

**Comment by Arnuh** [comment]
Closing as they are technically a 1.20 feature so any camel talk should be handled in #145 or #134 based on the reason, and bugs should be separate issues.
