### ISSUE TITLE
Horses are buggy

### ISSUE THREAD

**Issue by dejakob1** [Arnuh/EchoPet#14]
Whenever I ride a horse it lags really hard client-side. The horse barely moves and when I got off I get teleported where I was supposed to be with the horse.

**Comment by Arnuh** [comment]
Pretty sure its cause of #6, last time I tested.. anyone is entirely free to PR a fix.

**Comment by andrewkm** [comment]
It looks like it lags and doesn't follow your instructions at all client side.
However other players can see you riding around on the horse just fine.
In fact your usually glitched far away client side, meanwhile players see you in a totally different area as if you're riding just fine. Other than bumping into walls lookin all high cause you don't know where you are lol.

**Comment by andrewkm** [comment]
@Arnuh horses seem to be completely unmovable when riding still.

**Comment by Arnuh** [comment]
Enable the saddle.

**Comment by andrewkm** [comment]
Beautiful! <3
Works great lol.
