### ISSUE TITLE
Cannot change cat type anymore.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#141]
No idea why or what's up, nothing changed on our end with permissions, etc.
https://ecocitycraft.com/forum/threads/pet-not-letting-you-modify-your-pet.221961/

We'll investigate code when time allows.

Paper 1.19.4 Build 521
EchoPet up streamed to https://github.com/Arnuh/EchoPet/commit/cf1b5cb1da4e219b866f9b2cc8ccc46ceaa99c80

**Comment by Arnuh** [comment]
1.19 moved "cat variant" to a new entity data type

**Comment by electronicboy** [comment]
fwiw in relation to the linked thread; the UUID for the owner is no longer stored in a data syncher, removing that from .4 fixes the color stuff

**Comment by andrewkm** [comment]
Fixed, up streamed to https://github.com/Arnuh/EchoPet/commit/4465c78edaa29276eb89517de2be86bfb68a3481 and using https://i.imgur.com/J1JghKX.png (horse/llama colors).
All issues addressed.
