### ISSUE TITLE
Black/Red cat type not accepted when spawned via commands.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#144]
/pet cat:calico,tamed,magenta,sit;Arnold
Correct: https://i.imgur.com/ak7XfuT.png

/pet cat:red,tamed,magenta,sit;Arnold
Not correct: https://i.imgur.com/MkJzdWk.png

Seems that black and red are bugged via commands.
https://ecocitycraft.com/forum/threads/.222099/

**Comment by andrewkm** [comment]
damn hit accept too quick, editing title moment.

**Comment by Arnuh** [comment]
Cats have a collar & cat 'type' and they conflict in the cases you provide. Currently have to specify `type_red` and I think that should work

**Comment by andrewkm** [comment]
/pet cat:type_red,tamed,magenta,sit;Arnold
Worked: https://i.imgur.com/x0liHjV.png

Hm, alright, going to specify that somewhere to players as currently they getting confused lol.

**Comment by Arnuh** [comment]
Might be somewhat fixable in the future with #125 ? as you'd be able to do your own custom names and ignore the default while command suggestions would also recommend it.

Not sure on other alternatives as it is just a name conflict and it is just a color..

**Comment by andrewkm** [comment]
Alright, thank you for your responses.
We'll see what we can come up with after the weekend.

**Comment by andrewkm** [comment]
We've decided to ignore this issue and instead explain via our wiki how to use the command properly when there are overlapping choices. :)
