### ISSUE TITLE
BungeeCord proxy error when using Pets

### ISSUE THREAD

**Issue by MinecraftAdmin** [Arnuh/EchoPet#15]
![image](https://user-images.githubusercontent.com/1650123/29070631-d0154312-7c05-11e7-9096-add500763efe.png)

This happens when spawning a pet in running the /pet command on a server connected to through BungeeCord proxy.

Runnin Bungeecord 1.12.1

**Comment by MinecraftAdmin** [comment]
@Borlea Would appreciate feedback on this :)

**Comment by andrewkm** [comment]
I cannot reproduce this @MinecraftAdmin 
Please update your environment to the latest builds of everything and try again.
Perhaps it's an old issue now fixed.

**Comment by DesperoKF** [comment]
i have the latest BungeeCord with Spigot 1.12.2. I have this problem too. i using this as version: https://github.com/Arnuh/EchoPet/releases
