### ISSUE TITLE
Deprecated Event Usage in EchoPet: EntityDismountEvent

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#153]
Paper 1.20.4 Build 393

`[04:51:15] [Server thread/WARN]: [EchoPet] "EchoPet v1.4.0-SNAPSHOT-b125" has registered a listener for org.spigotmc.event.entity.EntityDismountEvent on method "public void com.dsh105.echopet.listeners.PetEntityListener.onEntityDismount(org.spigotmc.event.entity.EntityDismountEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [].`

**Comment by Arnuh** [comment]
what dumbass put it originally in the spigotmc package

also why lie about performance? Seems like they runtime fix this to the proper event


-- oh this is a very recent change...

**Comment by Arnuh** [comment]
https://github.com/Arnuh/EchoPet/commit/f6f2ee459ec072fe6ad017ef99b3e62328744966#diff-5416d9348bef959e7b9318cf255338d211c165cf40748072bfa8c4f6df7a76ad
