### ISSUE TITLE
1.12 support pls

### ISSUE THREAD

**Issue by TheIntelloBox** [Arnuh/EchoPet#17]
1.12 support pls

**Comment by Sandukhan** [comment]
There is a working version for 1.12 of echopets right here:

https://github.com/Borlea/EchoPet/releases

**Comment by DahunDev** [comment]
That's not works. The plugin says the craftbukkit is not compatiable.
I'am using lastest 1.12.2 spgiot

**Comment by Sandukhan** [comment]
Im using that plugin on my own 1.12.2 Spigot server for a while now and its doing fine. Look like you did something wrong.
