### ISSUE TITLE
1.13.1 support

### ISSUE THREAD

**Issue by TheIntelloBox** [Arnuh/EchoPet#21]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-1-development-builds.336415/

**Comment by TNTUP** [comment]
Subbing here' <3

**Comment by maartenvr98** [comment]
Same here. Is there an ETA for the 1.13.1 update?

**Comment by johnfriedrich** [comment]
I also would be very happy if it at least starts on 1.13.1. Thanks in advance!:) Hopefully you get some time for it

**Comment by maartenvr98** [comment]
I found a better alternative: https://www.spigotmc.org/resources/simplepets.14124/

**Comment by johnfriedrich** [comment]
Thanks, but we are using ProtocolSupport. EchoPet is written that it works without any issues with PS. SimplePets is not.
Aaand, we have hundreds if not thousands pets with custom names across different servers. Migrating them would be possible, but a pain. Will still look into it, thanks

**Comment by TNTUP** [comment]
@i9hdkill don't forget permissions :P I prefer EchoPet myself too :)

**Comment by Arnuh** [comment]
[Try this](https://mega.nz/#!P1ZzGaQb!AKKeunX_qhsRRcQQsVd0daB8wOcmcC0K97ST-uokqBQ)

R2 looks identical but I didn't do much testing

**Comment by johnfriedrich** [comment]
It might work, but fails due to EchoPet not compatible with WG 7
https://github.com/Arnuh/EchoPet/issues/25

**Comment by aurel85** [comment]
I have this error with the above version : https://pastebin.com/gAiNM6xs

I use PaperSpigot 1.13.1.

**Comment by johnfriedrich** [comment]
simply delete the trail section from your echopet config

**Comment by Arnuh** [comment]
Oh the test trails are broken... I'll replace the defaults whenever im available. Busy 2 days due to thanksgiving.

**Comment by aurel85** [comment]
Now that the plugin works at startup, he does not want to spawn mobs when I use the pet selector.

https://pastebin.com/QBGWjrZ5

**Comment by johnfriedrich** [comment]
Yep, as I mentioned above, the plugin isn't compatible with WG7
See here:
https://github.com/Arnuh/EchoPet/issues/25

**Comment by Arnuh** [comment]
[Current Version](https://mega.nz/#!P1ZzGaQb!AKKeunX_qhsRRcQQsVd0daB8wOcmcC0K97ST-uokqBQ)

**Comment by aurel85** [comment]
It works fine except for : 

- When using the pets this message appears quite regularly in the console : https://pastebin.com/mTTZJAiy

- The Enderdragon pet doesn't work _(bug not coming from this version from what I just read)_ : https://pastebin.com/cJsPqkZb

- ZombieVillager pet is invisible

**Comment by johnfriedrich** [comment]
This comes upo in console, but seeems to be working! Thanks
http://prntscr.com/l42jhx

**Comment by Arnuh** [comment]
The enderdragon issue was mentioned in #24 Which is due to some NPE on an object that is initialized so idk the exact cause. And I know about the console spam for null class but I haven't looked into why but I assume it's because the string I use for lookup is different compared to what mojang uses.

**Comment by Arnuh** [comment]
[Another update](https://mega.nz/#!P1ZzGaQb!AKKeunX_qhsRRcQQsVd0daB8wOcmcC0K97ST-uokqBQ)

If anyone knows how the command system is autohinting pets that would be helpful.. Since from the looks 1.13 ones aren't being suggested.

Also I just updated plugin.yml using that autogenerator thing I made in PetType and I have no idea how reliable that is.

**Comment by aurel85** [comment]
It's ok for the console with this version, there's no message, thanks !

**Comment by andfont** [comment]
Do not use the simplepets, it is incompatible with citizen, viaversion and more plugins is not well done! but echopet seems to work please to see if you can have them well for the 1.13.1 xD many thanks and good work to migos xD

**Comment by TheIntelloBox** [comment]
Hello, does the plugin work in 1.13.12 ? :D

**Comment by johnfriedrich** [comment]
Yes, it works on 1.13.2

**Comment by andrewkm** [comment]
This is done and the latest build can be found here:
https://ci.ecocitycraft.com/view/EchoPet/job/EchoPet/17/

Let's close this and make new issues based on the latest builds so we can keep things organized :)
