### ISSUE TITLE
Some pets do not work

### ISSUE THREAD

**Issue by maartenvr98** [Arnuh/EchoPet#24]
The following pets doesn't work on 1.13:
Enderdragon (Error in console)
Magmacube (I'm getting a slime cube)
Mushroomcow (I'm getting a normal cow)
Zombievillager (Pet is invisible. Nametag is vissible)

**Comment by aurel85** [comment]
It's ok for MagmaCube and MushroomCow but not for ZombieVillager and Enderdragon with the last version.

**Comment by Arnuh** [comment]
Dragon should work now.. Altho his flying seems broken but this code is literally hotfixed since 1.8 so I'm not really surprised.

**Comment by aurel85** [comment]
Effictively apart from the bug you reported (and that has been around for a long time) it works fine, thanks !

So he stays the bug with the ZombieVillager.

**Comment by andrewkm** [comment]
Update here:

Enderdragon (Error in console)
**FIXED**
Magmacube (I'm getting a slime cube)
**FIXED**
Mushroomcow (I'm getting a normal cow)
**FIXED**
Zombievillager (Pet is invisible. Nametag is vissible)
**NOT FIXED**

Updated results here:
https://github.com/Arnuh/EchoPet/issues/37

This can be closed.
