### ISSUE TITLE
EchoPet does not work with WorldGuard 7

### ISSUE THREAD

**Issue by johnfriedrich** [Arnuh/EchoPet#25]
Error:
https://pastebin.com/5fPN0Y5P

WorldGuard Build used:
http://builds.enginehub.org/job/worldguard/10414

**Comment by Arnuh** [comment]
Can you find a maven repo with worldguard 7.0?
I can just do a local lib folder with it I guess but avoiding that would be nice.

**Comment by johnfriedrich** [comment]
Asked yesterday in their discord because I was searching for a maven repo aswell, turned out there is none (for now)
http://prntscr.com/l2c00e
Btw, could you add dependencies like Robert/Minecraft-reflections etc into a lib folder aswell? Tried to fix it myself but ended up aborting it because couldn't get it to build even when putting offline libs into a local folder. Maybe I grabbed the wrong versions though

**Comment by Arnuh** [comment]
Probably wont be doing the local thing. So until a public repo is available it'll have to wait. And those 2 repos should be available on my git you just need to import it and build it with 'install' and you should be able to setup echopet fine.

**Comment by johnfriedrich** [comment]
7.0.0 Builds are on maven
http://maven.sk89q.com/repo/com/sk89q/
