### ISSUE TITLE
News mobs of the 1.13 ?

### ISSUE THREAD

**Issue by aurel85** [Arnuh/EchoPet#27]
Hi,

Is it expected that the new mobs of the 1.13 (dolphins, turtles, phantom...) be added ?

**Comment by Arnuh** [comment]
They should be added just maybe not in the selector/in the command hint thing? Which I don't even know how that works but I assume its config based.

They may be missing some things because I don't really keep up with minecraft and when updating didn't see much I could manipulate with from datawatcher objects.

**Comment by aurel85** [comment]
What about 2 months later ?

**Comment by Arnuh** [comment]
Again, more specific on what's missing?

**Comment by aurel85** [comment]
Add the new mobs 1.13 in /pet selector

**Comment by aurel85** [comment]
With the latest version there are no new mobs 1.13 but against there are duplicates that have been added on page 2.

https://sandbox.fr/images/uploads/original/1543758224.png
https://sandbox.fr/images/uploads/original/1543758239.png

**Comment by Arnuh** [comment]
I assume the 3 dupe eggs are vindicator, evoker, illusioner. Idk what spigot calls 'illusioner' so the spawn egg is set to vindicator `ILLUSIONER(PetType.ILLUSIONER, Material.VINDICATOR_SPAWN_EGG`
Also the selector UI is loaded via the config file so you either have to update it manually or just generate new config.yml and copy it over.

Although I can definitely look into checking what PetItems are missing in the config and automatically add them in a future commit.

**Comment by aurel85** [comment]
It's true, and I just did it so I will be able to close this problem, but yes, it might be a good idea to do it directly in the plugin in the near future.

Thank you for everything !
