### ISSUE TITLE
Jenkins issues.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#33]
Alright, I've set up a public jenkins for you here with the echopet job.
https://ci.ecocitycraft.com/job/EchoPet

Here are is the current problem:
Full log: https://ci.ecocitycraft.com/job/EchoPet/1/console
`[ERROR] Failed to execute goal on project EchoPet-Parent: Could not resolve dependencies for project com.dsh105:EchoPet-Parent:pom:1: The following artifacts could not be resolved: com.captainbern:Minecraft-Reflection:jar:1.0.2-SNAPSHOT, com.codingforcookies:robert:jar:1.0: Could not find artifact com.captainbern:Minecraft-Reflection:jar:1.0.2-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

Will need a pom fix or you to send me artifacts so I can deploy them to my repo and build off the local artifact.

PS: I set the job to Poll Jenkins every 5 minutes.
If you want to setup Github hook let me know and I'll get that done for you and provide the secret key.

**Comment by andrewkm** [comment]
@Arnuh
EchoPet view is here: https://ci.ecocitycraft.com/view/EchoPet/

So I did some work, and I got past the reflection:
https://ci.ecocitycraft.com/view/EchoPet/job/Reflection/
Fixed

Next issue was robert:
https://ci.ecocitycraft.com/view/EchoPet/job/Robert/
Fixed

And now I'm stuck on PowerMessage (https://github.com/DSH105/PowerMessage)
https://ci.ecocitycraft.com/view/EchoPet/job/PowerMessage/
Build Log: https://ci.ecocitycraft.com/view/EchoPet/job/PowerMessage/4/console
Build Log from EchoPet: https://ci.ecocitycraft.com/view/EchoPet/job/EchoPet/4/console

Seems to be an issue downloading from:
`[INFO] Downloading: http://repo.dsh105.com/com/dsh105/Commodus/1.0.2-SNAPSHOT/Commodus-1.0.2-SNAPSHOT.pom`
...onwards (this is where it hangs).

Any ideas?
Gotta fix this PowerMessage thing to finally build EchoPet, or get the files from you?

**Comment by andrewkm** [comment]
@dsh105 maybe you can help, since I see it's your repo I'm trying to pull from.

**Comment by Arnuh** [comment]
For Java 11 they have a branch which seems stable enough to build and run but you either have to use the docker install or compile the file yourself I think? I've just been waiting for any new info on a beta build cause everything google gives is based on the hackathon.

Also I have slightly modified version of any lib echopet uses
https://github.com/Arnuh/Commodus
https://github.com/Arnuh/PowerMessage

The error looks more like the jar built but is corrupt and not a valid zip/jar file.

**Comment by andrewkm** [comment]
Oh, nice, I’ll try to build off your repos soon as I get out of bed. :). Hopefully we can get a smooth Jenkins going.

**Comment by andrewkm** [comment]
@Arnuh Ayyyyy my work is done :)
https://ci.ecocitycraft.com/view/EchoPet/job/EchoPet/
Robert, Reflection, Commodus, PowerMessage all built.
Echopet is properly building now, however now you just gotta fix compilation with latest WG.

I've set the above 4 projects on 3 hour interval, because doesn't need to be polling that often.
Meanwhile I've set EchoPet to 5 minute interval, so latest is always there if you need testing.

Here's the compilation error:
Full log: https://ci.ecocitycraft.com/view/EchoPet/job/EchoPet/6/console
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project EchoPet-API: Compilation failure
[ERROR] /var/lib/jenkins/jobs/EchoPet/workspace/modules/API/src/com/dsh105/echopet/compat/api/util/WorldUtil.java:[54,99] cannot find symbol
[ERROR] symbol:   method asBlockVector(org.bukkit.Location)
[ERROR] location: class com.sk89q.worldedit.bukkit.BukkitAdapter`
This class: https://github.com/Arnuh/EchoPet/blob/master/modules/API/src/com/dsh105/echopet/compat/api/util/WorldUtil.java
Issues with your latest commit basically.

But yeah, jenkins is ready.

PS: Rolling back your latest commit, can confirm it builds fine on a test repo I made. But then we of course need the new WE/WG system working so rip. Will wait for you to fix.

**Comment by andrewkm** [comment]
Oh also, it doesn't seem like WE repo has 7.0 btw.
We had this same problem on some of our plugins, and had to upload the actual jars to the project lib.
http://builds.enginehub.org/job/worldedit/10607/download/worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar
http://builds.enginehub.org/job/worldguard/10609/download/worldguard-legacy-7.0.0-SNAPSHOT-dist.jar

Maybe that's the issue. Totally guessing tho.

**Comment by Arnuh** [comment]
Well they have a repo.. but it seems like they changed the API again? but I see no commits available on the git.
https://github.com/sk89q/WorldEdit/commit/f0070c111cfded36ce31b6f65337871f9859740f
Could be this commit?

**Comment by andrewkm** [comment]
Your latest change seems to have built:
https://ci.ecocitycraft.com/view/EchoPet/job/EchoPet/ @arnuh
