### ISSUE TITLE
Bug with /home after use pets

### ISSUE THREAD

**Issue by aurel85** [Arnuh/EchoPet#35]
Hi,

This bug is present for a long time but I wonder if anyone could solve it ?
When we use quite a lot of pets in a short time sometimes it happens that the player can not make any more orders of the type /home, teleportation commands actually.
It takes a disconnect to solve the problem, it is not dramatic but if it could be resolved it would be perfect.

**Comment by andrewkm** [comment]
I can use essentials /home just fine with a pet/pets.
Can you please elaborate more.

Which plug's /home are you using.
What exactly is happening.
Give exact reproduction steps.

**Comment by aurel85** [comment]
After the use pets for many minutes, so after /pet remove (via the /pet selector) some players sometimes can not do the command where they are teleported, like /home or /spawn.
There is nothing else special to say about this bug, no error in the console.
And a disconnect solves the problem.
I'm using EssentialsX and the bug has been around for a long time on my server.

**Comment by andrewkm** [comment]
I will test this and get back to you soon.

**Comment by andrewkm** [comment]
I cannot reproduce this no matter what I try.
You will need to give consistent, exact reproduction steps, otherwise nothing can be done.

This does not happen on my testing environment.

**Comment by aurel85** [comment]
The problem is that it's random and it does not happen constantly, so I can not tell you more about exactly how to reproduce it... It does not matter, we undergo this bug it for a long time and is not extremely serious.

**Comment by Arnuh** [comment]
Probably #41 ?

**Comment by aurel85** [comment]
I can't reproduce the bug so it seems to me corrected. 
But when I have a pet on the head /home or /spawn doesn't work. 
While when I ride it or it is by my side there is no problem.

**Comment by Arnuh** [comment]
The plugin has to demount the entity if it wants you to warp. That's a restriction of the API not a bug related to EchoPet.
