### ISSUE TITLE
Tested all pets on latest build (17)

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#37]
Latest build.
I've tested absolutely all pets.

Only issues I've found that remain are:

**Enderdragon** falls through the world when spawned.
**Enderdragon** riding has issues and is stuck going forward/backwards/down. Shifting it upwards seems fine. As does holding A or D for left and right.
**Riding horses** issue persists. https://github.com/Arnuh/EchoPet/issues/14

If anyone would like to add any bugs, please do and respond :) Trying to get a list together.

**Comment by andrewkm** [comment]
Zombie Villager pet confirmed fix.
Removed from the list.

**Comment by PhanaticD** [comment]
enderdragon just yeets off into the distance when spawned
