### ISSUE TITLE
Not working on 1.13.2?

### ISSUE THREAD

**Issue by Swede37** [Arnuh/EchoPet#39]
When trying to add the plugin, I get errors in console.  I tried the latest build first, went back and tried build #20 from Jenkins, no luck on either one of them.
 For what its worth, I'm running git-Spigot-f56e2e7-0c715b3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
https://pastebin.com/yTsCA0eH

**Comment by Arnuh** [comment]
Build 20 failed but 23 works fine for me on

> [16:00:36 INFO]: This server is running CraftBukkit version git-Spigot-f56e2e7-0c715b3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
> [16:00:36 INFO]: Checking version, please wait...
> [16:00:36 INFO]: You are running the latest version
> >

**Comment by Swede37** [comment]
Were there any new/ different dependencies?
I had tried build 23, and it showed active with ./pl, but trying ./pet, ./petselector and ./echopet didn't do anything? (As OP)

**Comment by Arnuh** [comment]
Only thing changed is updating to latest spigot NMS changes and worldguard/edit.

Error looks like the jar is corrupted/missing files. The jar for build 23 should be ![Size](https://im.arnah.ca/S7auJr.png)

**Comment by Swede37** [comment]
Redownloaded, now it works like a charm.  Not sure quite what happened there, but Thank You for the help, the players will appreciate it!
