### ISSUE TITLE
jenkins.codingforcookies.com Down

### ISSUE THREAD

**Issue by UberMC** [Arnuh/EchoPet#4]
http://jenkins.codingforcookies.com/view/All/job/EchoPet/

Server doesn't respond, can't build maven project either since dependencies are on that server.

**Comment by Arnuh** [comment]
Probably will never come up, currently I just have everything set to offline mode but I guess that doesn't help considering you guys don't have commodus, powermessage, minecraft-reflection.. I'll get around to uploading those 3 to my git sometime later.

**Comment by JamieSinn** [comment]
That would be great if you could upload the current versions. Trying to use the old versions I have isn't working.

**Comment by Arnuh** [comment]
@JamieSinn But doesn't your server have a custom version made from scratch?

**Comment by JamieSinn** [comment]
No, we don't. Investigated upgrading echopet, but found it too much of a hassle. We were investigating using another pets plugin instead but you updated and that caught the eye.

**Comment by Arnuh** [comment]
Interesting considering it takes 2 hours max to get EchoPet in a working state each version.. maybe a few more to make sure every new pet feature is setup correctly.

Also interesting to see an owner talk out of his ass. But I'll upload them since he did give me a good laugh for a few months.
