### ISSUE TITLE
Player entity getting stuck unable to teleport after wearing a pet as a hat.

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#41]
Paper dev 522
EchoPets dev 23

@Arnuh If you wear a pet as a hat and then subsequently remove the pet afterwards, you are unable to teleport whatsoever. With essentials tp / home, joining various arena plugins, multiverse teleporting, portal plugins, etc.

The player entity gets effectively locked into their current world location when they equipped the pet hat.

**Comment by Arnuh** [comment]
I think I talked about this issue before and it's not something I can fix and is 100% the teleport plugins fault.

CraftEntity#teleport has a check
`if ((this.entity.isVehicle()) || (this.entity.dead)) {
   return false;
}`
It's expected for the teleporter plugin to check this and demount the entity(pet) from the player before teleporting them.

**Comment by Arnuh** [comment]
untested.. but it should work

**Comment by mibby** [comment]
@Arnuh Thanks, I'll give it a test. Jenkins didn't seem to compile the build so will need to manually compile.

**Comment by Arnuh** [comment]
It'll prob build eventually but idk.. I need to setup echopet on my own jenkins someday now that it's supported somewhat on java 11(altho not fully and some plugins complain about jaxb still)

@andrewkm btw since I know you asked about java 11 support. It mostly works with latest weekly but I had to remove java check in jenkins service file and on current weekly you need to add an arg to support future java versions(But I saw a commit to fix this one)

**Comment by mibby** [comment]
I've actually been using Java 11 with EchoPets for the longest time. Only recently did I change back to Java 8 due to plugins complaining about javax SSL no psk available during update checks. Reflections hasn't been removed yet in Java 11 so everything for the most part works great. :)

**Comment by andrewkm** [comment]
@arnuh Jenkins polls for changes on EchoPet every three hours. If you want instant push to my jenkins please DM me for the hook information and secret key.

**Comment by Arnuh** [comment]
@mibby I meant jenkins supporting 11 but yeah echopet should work on it fine as its my daily.

And I'm sure 3 hours is fine for now

**Comment by mibby** [comment]
@Arnuh Using EchoPets dev 24, commit https://github.com/Arnuh/EchoPet/commit/c9f6cbe5fba95a5709a1abee843df7d045cd0b5a didn't seem to fix the issue entirely.

* /pet cow
* /pet hat
* /pet remove
* /spawn

You are unable to teleport.

However..

* /pet cow
* /pet hat
* /pet hat (to remove it from your head but keeping the pet)
* /spawn

You are able to teleport.

I assume pet hide would also break it since it removes the entity directly while you are still in a "vehicle" state.

**Comment by mibby** [comment]
@Arnuh My guess is the player entity vehicle state isn't being properly cleared when the pet entity is removed while riding?

**Comment by mibby** [comment]
Confirmed fixed, thanks!
