### ISSUE TITLE
1.14 support

### ISSUE THREAD

**Issue by Arnuh** [Arnuh/EchoPet#46]
First somewhat tested version is available here https://github.com/Arnuh/EchoPet/tree/v1_14_R1

Fox item is set via item in inventory?
Pillager crossbow is set via inventory.
Allow customizing PetData/PetDataCategory items
Rework `generatePetInfo` and `generatePetDataInfo` to be a method inside each pet.
Make pufferfish do sounds when you increase or decrease its size. `ENTITY_PUFFER_FISH_BLOW_UP` and `ENTITY_PUFFER_FISH_BLOW_OUT`
Also probably should readd EnderDragon but I'm at the point idc to continue fixing it.

I'll try to keep this updated with what im doing.

Server Owner Notes:
If you notice any permission issues make sure to create an issue.
- I reworked the petdata completely so certain names might have been changed resulting in permission changes.
- I also specify hat/ride more like a "PetData" so it no longer has a specific permission node it instead goes under the same path that other petdata is under. Example: `echopet.pet.type.zombievillager.hat`. it still has a parent permission node to give hat/ride for ALL pets.

**Comment by Arnuh** [comment]
Does a point exist in supporting versions that aren't the latest? Only reason any server does something lower than latest is because plugins aren't updated or controversial changes were done.

**Comment by andrewkm** [comment]
@Arnuh 

Added if you still need:
1.13.2: https://ci.ecocitycraft.com/job/EchoPet%201.13.2/ (Builds off master)
1.14: https://ci.ecocitycraft.com/job/EchoPet%201.14/ (Builds off v1_14_R1)

If you need instant push well need to setup webhooks. You can DM me for that if needed. Right now it polls every 3 hours.

**Comment by johnfriedrich** [comment]
No, support for other versions than latest are not neccessary, if the plugin of the old version works. And the 1.13.2 version is quite ok. So should be totally ok to only support latest, like ProtocolSupport does it aswell

**Comment by TNTUP** [comment]
EchoPet for 1.13.2 on PaperSpigot 1.13.2 throws me that error https://pastebin.com/E8PgczGB. Since the EchoPet 1.13.2 CI link was given here, I thought posting this here. Else, I'll make my own issue then delete this comment if requested.

I'm still glad you're still on Echopet even for 1.14! <3

**Comment by DesperoKF** [comment]
Can you make a 1.12.2 Version ? pls. I hate the new Pet Plugins

**Comment by DesperoKF** [comment]
> 
> 
> No, support for other versions than latest are not neccessary, if the plugin of the old version works. And the 1.13.2 version is quite ok. So should be totally ok to only support latest, like ProtocolSupport does it aswell

Many Servers use 1.12.2 too. EchoPet for 1.12.2, 1.13.2 and 1.14 for the latest 3 MC Version. When 1.15 comes drops the 1.12.2 from updating...

**Comment by johnfriedrich** [comment]
Maintaining more than one mc version is a pain if it comes to echopet. I recommend to upgrade to 1.13.2 as it's rockstable and all plugins are available for it. There is no reason not to. Reason could only be using bad plugins or lazyness. EchoPet for 1.13.2 works fine. Anyway, this issue is for tracking 1.14 status

**Comment by DesperoKF** [comment]
Well version 1.12.2 update never came. I would like to use EchoPet instead of the new Pet Plugins

**Comment by Arnuh** [comment]
1.12 is prob not too bad and a version did come out for EchoPet 1.12.

Looking at changelog of 1.13 it looks like it'll be easy to support 1.12 if I'm also supporting 1.13 but i'm currently doing 1.14 with 0 care about 1.13 so you'll likely have to wait awhile.

**Comment by DesperoKF** [comment]
But 1.12 is not 1.12.2. Its give with 1.12 Packet errors on 1.12.2. 

I hope you can make a 1.12.2 Version from EchoPet. :D

**Comment by johnfriedrich** [comment]
Thre change from echopet.pet.ride to echopet.pet.type.creeper.ride and same for hat is kinda ugly, at least for existing servers.
It probably make sense, but we sell different kind of pets, but if you buy riding, you can ride all of them. That was kind of easy because echopet.pet.ride existed. Now we have to add this permission for each new pet for each update for every player on every server. Thats kinda a mess.

Nevermind, the permission didn't change technically:D

**Comment by Arnuh** [comment]
@i9hdkill Yeah I think it should still work for the case you described as I provide the parent permission node `echopet.pet.ride.*` which gives the pet specific node `echopet.pet.type.<type>.ride` for all

**Comment by aurel85** [comment]
There is news ?

I have an error to remove my pet in 1.14.2
With pet toggle in GUI : https://pastebin.com/n8MqHpAp
With /pet remove : https://pastebin.com/0eUnb6CR

I use PaperSpigot 1.14.2 and the last version of this plugin.

**Comment by Arnuh** [comment]
Ok the panda is the cutest thing ever.

Since the stances are flags like foxes you're able to combine multiple and make him do some funky stuff. Plus we can keep things like "Sit" active while he moves.

**Comment by Arnuh** [comment]
So a possible issue where certain pets have PetData that are duplicate and if you give 1 permission node they get both.

Examples are Cats with Collar and Type which for example share red, white, black. Pandas with Main/Hidden Gene(altho not a huge issue with how it works)
Fixes are to just create 2 entries for each or separate PetData permission when within a category by the category name or just leave it as is for now.

I'll probably just fix the tropical fish and cat by creating duplicate petdatas or using different ones and leave the panda as is.

**Comment by Arnuh** [comment]
1.14.4 added an extra arg to a pathfinding method that seems to behave similarly to echopets distance between player & pet to force a teleport, but instead it's the distance between player & pet before it starts to path(at least from my testing). [Here is a link](https://github.com/Arnuh/EchoPet/commit/f7741aa07baf21cf392aa2e33d371c13abc3cb8a#diff-887537841f8eac1e19299c7eefc1734fR128)

Currently it's setup to a static 3(2 also seems good) but i'll likely implement it later to work like teleport.

I also just noticed echopet already has a `startFollowDistance` which sounds like its the same but it's implemented manually in EchoPets shouldStart check but the values don't seem to really match as 12 would just make the mob hit teleportDistance(Just did another check, looks like echopet calls a method that does squared where minecraft doesn't which means 12 is actually 3.46 for this arg and looks like I did a good guess)

**Comment by Arnuh** [comment]
Not entirely sure how many people actually use this plugin and with 1.15 being confirmed for Dec 10th(From what I saw) I likely wont be finishing whatever is left on this todo list before that date due to other projects of mine taking priority.

Because nothing gamebreaking has been reported for 1.14(pretty sure 1.13 is busted atm but that's an issue for later) I'll be merging this to master once 1.15 comes out and copying whatever is left to the 1.15 issue. 

Also please md5 use mojang mappings.. I know you wont but please do.

Another also... I'll be supporting 1.14 on the 1.15 branch so if you need any of the features left on the todo and assuming the 1.15 branch is stable enough you can just use that.

**Comment by TNTUP** [comment]
Myself, still using it on my 1.12.2/1.14.4^^

Edit: nice Arnuh!

**Comment by aurel85** [comment]
I use the plugin and I still intend to use it :)

**Comment by andrewkm** [comment]
Still using it on 1.13.2 and 1.14.4 and soon 1.15 :) Thanks for continuing with the updates!

**Comment by andrewkm** [comment]
@Arnuh you may wanna update the download link to: https://ci.ecocitycraft.com/view/EchoPet/ which is the view.

Since there are now two jobs, one for 1.13.2 and one for 1.14.4 and eventually will make one for 1.15 :)

**Comment by johnfriedrich** [comment]
I am also using this plugin on 1.14.4. Each major mc update I am happy af that such an awesome person updates echopet each time! 😍

**Comment by TNTUP** [comment]
I'm very glad EchoPet is still supported as I'm planning to make a new 1.15 survival

**Comment by andrewkm** [comment]
All I want for Christmas is the legendary EnderDragon to somehow one day get some love <3 lol.

**Comment by andrewkm** [comment]
@Arnuh 
Hook a brother up with: https://github.com/Arnuh/EchoPet/pull/53
