### ISSUE TITLE
1.15 support

### ISSUE THREAD

**Issue by Arnuh** [Arnuh/EchoPet#55]
I honestly got 0 idea what came out in 1.15 other then bees and new rendering stuff?(Plus I hear the game prioritizes chunk loading over high fps)

General todo list:
Iron Golem cracking(set hp)?
All the 1.14 stuff I forgot.
Fox item is set via item in inventory?
Pillager crossbow is set via inventory.
Proper flying ai.
Allow customizing PetData/PetDataCategory items
Rework generatePetInfo and generatePetDataInfo to be a method inside each pet.
Make pufferfish do sounds when you increase or decrease its size. `ENTITY_PUFFER_FISH_BLOW_UP` and `ENTITY_PUFFER_FISH_BLOW_OUT`
Also probably should readd EnderDragon but I'm at the point idc to continue fixing it.
Also still have Parrots and Shulkers?

Looks like 1.15 nms isn't using mojang mappings making this a very sad day.

Also if you haven't checked the 1.14 issue I suggest reading it as some possible breaking changes happened. https://github.com/Arnuh/EchoPet/issues/46

**Comment by andrewkm** [comment]
Damn boy you quick! <3

**Comment by Arnuh** [comment]
```
public double lastX;
private double locX;
```
ah yes make 1 private but not the other

Also if anyone wants to test.. The below commit seems to work fine so far for me. Riding, some basic petdatas all work.

**Comment by andrewkm** [comment]
For those ready to test..

Main view:
https://ci.ecocitycraft.com/view/EchoPet/

Master Branch:
https://ci.ecocitycraft.com/view/EchoPet/job/EchoPet/
v1_14_R1 Branch (1.14.4):
https://ci.ecocitycraft.com/view/EchoPet/job/EchoPet%201.14.4/
v1_15_R1 Branch (1.15):
https://ci.ecocitycraft.com/view/EchoPet/job/EchoPet%201.15/
All above poll once every 3 hours.

I myself am a good month off from 1.15 as always.
Thanks for the quick work though @Arnuh

**Comment by Arnuh** [comment]
I would probably rename the one polling master to just EchoPet as I've already merged 1.14 into master. Should have probably made a branch off master to keep 1.13 alive but if 1.15 isn't too bad I'll have some extra time to fix up 1.13 > 1.15 anyway

**Comment by andrewkm** [comment]
Alright done and edited above links :)

**Comment by TNTUP** [comment]
That would be funny with the Pufferfish sounds, with the pet, if I approach another player or a mob it would go big XD I guess that won't be possible but thats just an idea XD 

Keep the good work Arnuh, seeking to test it soon

**Comment by Arnuh** [comment]
Couple recent commits should add back some support for 1.13. Not sure how much is broken but at least the plugin loads and I can do some simple tasks.

Also hat/riding is a bit weird and requires extra toggle of hat/ride in some cases. Not sure if its an issue with the shift unmount not resetting riding as false or just some other issue.

Ok somehow /pet rider cow when I already have a cow is spawning a pig... interesting

**Comment by andrewkm** [comment]
If possible, can you make EchoPet respect WG and it’s entry region flag.

As it stands you can enter a WG region with entry: deny while riding a pet. By dismounting, you properly get booted off the property, however it shouldn’t even be possible to enter in the first place.

Would be really cool if it wasn’t difficult to fix :)

**Comment by Arnuh** [comment]
Sounds like that check would replace the current check we have as it would be changed via the person who owns the region ingame instead of some messy echopet config check

Also are you able to ride normal horses/pigs into the WG region and not get kicked out? Or does WG just have some weird issue with pets.

And this should go into its own issues.

**Comment by andrewkm** [comment]
Alright, I've now tested and made a separate issue for it :)

**Comment by andrewkm** [comment]
@arnuh I've also opened up a few separate tickets of minor issues with pets.
Not sure if you wanted all those in here or as separate issues.

**Comment by andrewkm** [comment]
@Arnuh please push dad
https://github.com/Arnuh/EchoPet/pull/65/commits/6dd0aaefbb99189a144dd9c40d8a15ba8b273ce4

**Comment by Arnuh** [comment]
It already is. That PR is based on the master branch.
https://github.com/Arnuh/EchoPet/blob/v1_15_R1/src/resources/plugin.yml#L1985

Also does anyone know when flying mobs stopped flying(more like floating)?

**Comment by andrewkm** [comment]
FINE, I stoopid :( lol. How the fuck did I miss that, I swear I looked through the commit before making that PR. I'm trippin.

Also, can you elaborate on the flying mobs stopped flying @Arnuh not sure what you mean?
Like /pet bee for example?

https://i.imgur.com/YQJ2wzP.png

Man it's been like that for quite a while, no idea when it broke.
They kinda just tokyo drift around lmao.
