### ISSUE TITLE
WorldGuard entry flag can be bypassed.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#57]
Config:

`worldguard:
  regions:
    echopet: true
    allowByDefault: true
  regionEnterCheck: true`

Riding a pet bypasses the entry flag allowing you to enter the region.
Riding a regular horse with a saddle does not bypass the flag and works fine.

Something on EchoPet's side that's causing this.

**Comment by Arnuh** [comment]
Sounds like some check worldguard has for no reason breaking it on pets.

Also the current worldguard support is kinda ugly and seems like expensive calls so figuring out if I can just delete it and rely on worldguard would be better.
