### ISSUE TITLE
Pet fox is missing pounce in DataMenu

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#59]
This should be pounce.
https://i.imgur.com/y2TZ5r9.png

Instead it shows HeadTilt which is a duplicate of the one before it.
https://i.imgur.com/VCICiKt.png

As well, clicking on the pounce thing, doesn't seem to do anything, so there's likely a small slip up when adding fox <3

**Comment by Arnuh** [comment]
Pounce works but I guess it needs something to reset it because it wont work after it gets toggled once.

**Comment by andrewkm** [comment]
Weird, it’s not doing anything for me.
The typo is fixed, but the actual pounce does nothing.
