### ISSUE TITLE
Unknown mob entity network type id 1,864

### ISSUE THREAD

**Issue by TNTUP** [Arnuh/EchoPet#64]
Hey, since 1.14.4 I've been seeing reports of players with that kind of kick/crash error and I try to pinpoint to the culprit and the only plugins that creates custom entities.

The server uses ProtocolSupport, I'm guessing its probably a plugin with custom entities like EchoPet, ProCosmetics etc... I did testing without ProCosmetics and the issue still occurs and I thought of EchoPet. Now I'm testing it without EchoPet and reporting back on this.

Can't really say if its due to ProtocolSupport itself, if it occurs again without EchoPet I might close this ticket and report it to ProtocolSupport devs instead.

I've done a pastebin of ProtocolSupport's debug command, https://pastebin.com/eRmdWs4u 

Either both plugins are the issue or ProtocolSupport. I don't have such issues on my 1.12.2 server (I use ViaVersion/ViaBackwards) but not on 1.14.4/1.15.1 which is ProtocolSupport.

Sorry if theres bad grammar or what, not my native tongue :)

**Comment by Arnuh** [comment]
I looked at a couple github issues protocolsupport has and it might be due to them not really being nice with non-mojang stuff.

I don't really know where this entity network id comes from but maybe I could fake it as the proper one? If the issue is we're generating new entity ids for each custom entity object for the pets then maybe it's fixable on my end.. If I can't fix it you're pretty much out of luck.

**Comment by TNTUP** [comment]
I've been trying to pinpoint to the issue, now I'm testing without EchoPet and if it occurs again that would be PS's fault. I'll report on that later

It's okay, just a shame I cannot find the problem :/

**Comment by TNTUP** [comment]
Hey, I noticed when I checked out my logs folder and I looked at a file (because I remember the server crashed thereafter I  tp'd to the player and I got kicked and somehow the server crashed, could be something to help? Can't really say if its due to this or what, ProtocolSupport? 

Giving you the pastebin of it https://pastebin.com/T1QkLv2H, hope it can help you^^ You'll see something at the top, somewhere "Timing stack corruption" and it spammed a huge log of stacktrace related to EchoPet. Let me know if this could be the problem since 1.14.4 (and I guess no backport of it, if not anyways I'm planning to update the creative server to 1.15.1)

Edit: Does EchoPet has a debug option?
Edit2: I haven't tested EchoPet on Spigot 1.15.1 server w/ PS. The time it takes to make it happen is rare :/
Edit3: Happened again on the 1.14.4 server, im out of luck... Does EchoPet makes custom entities? How I can debug/get a list of network entity ids? Is there a plugin that prints me all entity ID/Network entity IDs so I can debug/know what plugin created this unknown mob ID? I'm quite desperate as I cannot do much anything to solve it

**Comment by Arnuh** [comment]
I have no info about network entities but I can look into it.

Also your pastebin does seem to point to echopet but I have no clue why that's happening as it seems to be an infinite loop somehow. I'm probably going to apply a change to how we handle 'enabling' pets to maybe help but I kind of doubt it

**Comment by TNTUP** [comment]
> I have no info about network entities but I can look into it.
> 
> Also your pastebin does seem to point to echopet but I have no clue why that's happening as it seems to be an infinite loop somehow. I'm probably going to apply a change to how we handle 'enabling' pets to maybe help but I kind of doubt it

Hm, I hope somehow this gets resolved :/ I couldn't find a plugin that would print me entity ids or entity network ids so I can report to devs. Else I don't know why and which plugin causes this on 1.14.4/1.15.1 servers :/

**Comment by TNTUP** [comment]
Heya, I can't seem to reproduce my own issue since you've made this commit https://github.com/Arnuh/EchoPet/commit/a9e9bdb16b20c053474039d46be57784b1c99fe1. 3 days from now on and no issues atleast 

I'm not calling it as a victory XD but if the issues arises again, I'll let you know :)
