### ISSUE TITLE
Cat collar not working. Instead always changes type.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#67]
Recently got the following report. Verified it myself.
https://ecocitycraft.com/forum/threads/bug-report-cat-collar-issue.193897/

**Brief Description**:
Cat Collar color changes cat type instead of collar color.

**Instructions**:
1. Spawn /pet cat
2. Right click cat and select red, white, or black collar color (can be tamed/untamed.)
3. Cat type changes instead of applying collar color.

**How many times did you recreate this?**:
Every time testing it

**Result**:
Cat type is changed instead due to duplicate names in collar color and cat type.

**Expected Result**:
Collar color is applied instead.

**Evidence**:
https://www.youtube.com/watch?v=1_4YaKjBHhQ

**Comment by Arnuh** [comment]
```
CAT has dupe perm string red one from data RED and category CAT_TYPE
CAT has dupe perm string white one from data WHITE and category CAT_TYPE
CAT has dupe perm string black one from data BLACK and category CAT_TYPE
```

Definitely never saw this coming.

I have partial support for using the same petdata in different categories but then saving, loading, permissions break it entirely :)

**Comment by andrewkm** [comment]
Confirmed fixed.
