### ISSUE TITLE
Rare issue: Farm animals despawning

### ISSUE THREAD

**Issue by TNTUP** [Arnuh/EchoPet#74]
Let me explain it. I've updated EchoPet this Wednesday and based on this commit https://github.com/Arnuh/EchoPet/commit/a726c7cd742dbe0b4c7820e95c13c07a02f0b1d3 could be the cause. 

Haven't tried past commits until this one is safe/fine to use https://github.com/Arnuh/EchoPet/commit/a9e9bdb16b20c053474039d46be57784b1c99fe1 (This commit probably fixed the unknown entity mod id shiz) so I downgraded to this one and I didn't get any reports about farm animals missing. 

Yes, they were breeded and I had cows, sheeps and chickens. One of my alts afked at my base so they should be stayed alive! However, the player who reported me the issue noticed his pigs/cows despawned BUT only tamed wolfs/cats/llamas was present. This cannot be the reason "You need to name tag them" as I never instructed my players to name tag their farm or I never did that since Minecraft exists. Can't really say if its the cause of the server software I use, PaperSpigot... 

I have no way how to reproduce it but it could happen but rarely. I had a similar bug way back in 2013 when it was Citizens which caused farm animals to despawn. So thats why I'm writing this issue as probably the last commis could be the cause. 

PS: I'll update my Creative server to 1.15.1 and might try the latest EchoPet build there.

**Comment by andrewkm** [comment]
This is not an echopet bug.
This is a confirmed bug using old versions of Minecraft with viaversion on 1.15.x in certain environments.

Update your server.
@armah can close this.

PS: The commit you linked are changes to plugin.yml and is completely irrelevant.

**Comment by TNTUP** [comment]
> This is not an echopet bug.
> This is a confirmed bug using old versions of Minecraft with viaversion on 1.15.x in certain environments.
> 
> Update your server.
> @Armah can close this.
> 
> PS: The commit you linked are changes to plugin.yml and is completely irrelevant.

I'll close the issue then. It might have changed in 1.15.2. The server was in Beta state and one of my staff members reported me and aswell mine were gone. Thanks for your answers ^^
