### ISSUE TITLE
Wandering Trader Baby Pets Broken.

### ISSUE THREAD

**Issue by andrewkm** [Arnuh/EchoPet#76]
Wandering Trader's have the baby permission in plugin.yml
However, do those things even have a baby variant?
Trying it in game does nothing to the wandering trader, it just moves the pet name tag onto the middle of their body.

https://www.youtube.com/watch?v=sbXUVzWhY64&feature=emb_title

**Comment by Arnuh** [comment]
They extend off villagers which then extends off ageable making the plugin automatically give it baby handling. It all exists on the server/client just I guess mojang did something to prevent the shrinking.
