### ISSUE TITLE
EchoPets delays start-up initialization by over 15 seconds.

### ISSUE THREAD

**Issue by mibby** [Arnuh/EchoPet#8]
@Borlea Compiled as of https://github.com/Borlea/EchoPet/commit/9ffe50f8e22b0ebd98bb6d1a5a3f7933ad878322

Start-up time is delayed by over 15 seconds with your fork of EchoPets. 

```
[07:55:46] [Server thread/INFO]: [WGNoFlyZone] Hooked into WorldGuard 6.2.2-SNAPSHOT;1708-3a8e3e8
[07:56:01] [Server thread/INFO]: [EchoPet] Enabling EchoPet v1.0.4-SNAPSHOT-b
[07:56:01] [Server thread/INFO]: [EchoPet] [INFO] [VanishNoPacket] Successfully hooked
[07:56:01] [Server thread/INFO]: [EchoPet] [INFO] [WorldGuard] Successfully hooked
```

And here it is again with a different plugin loading in-between to show it isn't caused by WGNoFlyZone.
```
[07:53:23] [Server thread/INFO]: [Plan] Player Analytics Enabled.
[07:53:39] [Server thread/INFO]: [EchoPet] Enabling EchoPet v1.0.4-SNAPSHOT-b
```

**Comment by mibby** [comment]
Suspected this is a problem due to the hundreds of static variables used since it is loaded before the plugin is enabled. I assume it is checking EchoPets and all plugins since it gets longer the more plugins that are installed.

A whole 15 seconds increase in start-up time is crazy. Some static accessed method or variable is doing stuff it should not do or do better.

**Comment by Arnuh** [comment]
EchoPet has a decent amount of reflection so I don't expect it to be fast.. but I'll try to see where the main delay is from sometime in the future and look into decreasing it.

**Comment by mibby** [comment]
Thanks. I don't remember your 1.10/11 fork being as slow during start-up initialization, so it could be a change in how Spigot handles static variables and reflections or java 8 in general. Unless of course you rewrote a significant part of the old fork to use static variables or unintentionally introduced this issue.

In any case, any optimizations would be appreciated!

I also tried manually updating all poms to compile against java 8 and spigot 1.12, as well as removed all lower versioned modules. Didn't seem to resolve the issue and the API failed to compile against java 8 due to here. https://github.com/Borlea/EchoPet/blob/7f23ee03a5df2be9cec49110798eab336cde5dbe/modules/API/src/com/dsh105/echopet/compat/api/util/wrapper/WrappedGameProfile.java#L66

**Comment by Arnuh** [comment]
Mine took 0.2seconds to load according to my logs. This is just on my pc which will most likely have a better cpu than most servers and with less plugins, so I'm interested in the results for you.
Result: https://hastebin.com/qucejujako.md

I suggest to not use this jar on a live server for more than to get the log times as it has incomplete parrot shoulder code.

**Comment by mibby** [comment]
When EchoPets actually begins initialization, it doesn't take long. It is the pre-initializing that lags. Assuming caused by the static accessed methods or reflections that are loaded before the plugin. More plugins installed, longer it takes EchoPets to load.

**Comment by Arnuh** [comment]
I don't know of anything that would cause a delay before onEnable is called other then the reflection in PetType.

Also don't understand how it would increase based on plugin count, as the only plugin related task is the hooks

**Comment by mibby** [comment]
Here is a zip of the plugin folder minus premium plugins and censored important information so you can test start-up behavior locally. Still has a 15 second start-up delay with 62 plugins.

Please remove the link as soon as you have it downloaded.
```
[17:33:40] [Server thread/INFO]: [Plan] Player Analytics Enabled.
[17:33:55] [Server thread/INFO]: [EchoPet] Enabling EchoPet v1.0.4-SNAPSHOT-b
```

> Also don't understand how it would increase based on plugin count, as the only plugin related task is the hooks

I don't either, unless something on pre-initialization of EchoPet is scanning all plugins for using the same events, reflections, or something. But the delay does get longer the more plugins there are. As previously mentioned, I do not recall your old fork having this issue, so I'm not entire sure what changed in the new fork or in spigot 1.12. :(

**Comment by Arnuh** [comment]
Seems I got a 9 second delay on my pc.. hmm

**Comment by mibby** [comment]
Is the use of all the static accessed methods important and can they not be replaced? From my quick research and info dump from @slipcor, they are slow to use.

**Comment by Arnuh** [comment]
Gimme some links for all these static variables

**Comment by mibby** [comment]
https://github.com/Borlea/EchoPet/search?utf8=%E2%9C%93&q=static&type= ?

**Comment by Arnuh** [comment]
21 pages not bad

**Comment by mibby** [comment]
It is only an assumption as to what may be causing the hang, not certain that is the true cause. But here's hoping.

**Comment by Arnuh** [comment]
ohwtf I just realized every datawatcher is static

Guess to add.. most of the static is used in the API, I don't know if it can be removed

**Comment by mibby** [comment]
So then this would be a spigot issue? Is there any way to debug the pre-initialization of what EchoPets is loading?

**Comment by Arnuh** [comment]
[19:52:18 INFO]: [Plan] Player Analytics Enabled.
[19:52:18 INFO]: [EchoPet] Enabling EchoPet v1.0.4-SNAPSHOT-b

After spending 15+ minutes with a profiler on the server(Made the startup time take forever).. I found something that seemed to have caused it.

Its the 2k permissions in plugin.yml. Open the jar, edit the plugin.yml, remove the 2k lines of permissions, save, startup server.. it'll be instant

**Comment by mibby** [comment]
Huh, odd. That does seem to speed it up to near instant initialization. Why does it hang on permission checks in the plugin.yml?

I'm assuming it gets longer with more plugins due to there being more overall permissions being injected. Would permissions still be handled properly and not given to everyone by default without the plugin.yml? Could it be due to the way EchoPets checks for permissions?

**Comment by Arnuh** [comment]
Its just bukkits/spigots setup for permissions.. it does more and more checks when adding new permissions, and when adding a total of 2k lines of permissions it makes it take forever.

**Comment by mibby** [comment]
So then outside of looking into optimizing how bukkit/spigot handles permissions, there is no way to fix this issue without removing all the permissions in the plugin.yml? 😕 

> Would permissions still be handled properly and not given to everyone by default without the plugin.yml permission delegation?

**Comment by mibby** [comment]
For reference.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/permissions/Permission.java#209

**Comment by Arnuh** [comment]
Doing a bit of testing and looking at bukkit wiki.. The only reason to add a permission node to plugin.yml is to configure it more, the options are default, description, children.

So if the default is set to op by default in bukkit/spigot we can remove all the permissions in plugin.yml that don't give children which is around 1200 lines.

If you would like to do some testing before I just destroy 1.2k lines from the plugin.yml that would be great.

**Comment by mibby** [comment]
The reason for using a plugin.yml to delegate permissions is so you can have permission defaults and not be forced into adding potentially hundreds of permission nodes to various groups. Or to use the children inherited wildcard groups for easy one permission 'bulk' permissions.

If EchoPet doesn't grant any permissions to anyone by default in the source and still checks for the node for functionality use, then it may be safe to remove the permissions from the plugin.yml to resolve the issue. I'm all for a plugin.yml clean-up to reduce the size. However, this seems like a grander overall problem within how bukkit/spigot checks bulk plugin.yml permissions.

I'm always down to do some more testing.

**Comment by mibby** [comment]
@Borlea Hopefully got it fixed here. Wonderful IRC experience in spigot...
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/c86a051a8ee61331cf827c429030ba056fb3aa0d#src/main/java/org/bukkit/plugin/SimplePluginManager.java

**Comment by Arnuh** [comment]
Interesting, nice

**Comment by Arnuh** [comment]
@mibby also glad you got md5 to do it despite him saying unable to reproduce.. as yeah, it isn't noticeable unless you have other plugins too.

I'm going to call this 'fixed' for now, but open another issue to look into reducing the permission count in plugin.yml
