### ISSUE TITLE
Can't open menu with right click unless looking at a mob

### ISSUE THREAD

**Issue by c0wg0d** [Arnuh/EchoPet#83]
I am SO HAPPY to have found this plugin updated to (mostly) work on 1.16.3!

Is this plugin still being maintained?  If so, I hope this issue can be fixed.

I can't right click on air or a block to open the pet menu with the bone in my inventory.  I have to click on a mob for it to open.  Can this be changed?

**Comment by Arnuh** [comment]
It works fine for me on 1.16.3

**Comment by c0wg0d** [comment]
Well it's definitely happening.  Have you tested it on Paper?
