### ISSUE TITLE
Reduce the permission count in plugin.yml

### ISSUE THREAD

**Issue by Arnuh** [Arnuh/EchoPet#9]
This should be fixed as of the latest spigot release(due to #8) but I think removing the unneeded data in the plugin.yml would still be a benefit just needs proper testing to make sure removing certain things doesn't cause any other issues.

**Comment by andrewkm** [comment]
The extensive amount of data in plugin.yml (regarding permissions) is actually really beneficial to me. Unless there are dupe entries I don't know about. I do like the setup and do not experience the hang issues mentioned in #8.
