### ISSUE TITLE
Suggestion: Add option to give Bow to Skeleton/Stray.

### ISSUE THREAD

**Issue by Waterman1001** [Arnuh/EchoPet#95]
#### Description

I noticed that when spawning a Skeleton Pet, it spawns without having a bow.
Of course this generally is fine, since you still have your skeleton pet.
However, I think it would be cool if you would be able to toggle it having a bow or not in the EchoPet DataMenu, since in the majority of cases you of course encounter a skeleton holding a bow.
I think they even spawn with a Bow if you use a Spawn Egg in creative mode.

Update: I noticed the same thing for Stray's. It would be cool if Strays would get the same option. :)

#### Version

While testing, I was running version git-Paper-71 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

**Comment by Arnuh** [comment]
Closing this for a bit more detailed todo on this subject here #97
